timeout: 3

/Mesa OS v0.1.0
    protocol: limine
    kernel_path: boot():/boot/mesa_kernel

/Mesa OS (Recovery)
    protocol: limine
    kernel_path: boot():/boot/mesa_kernel
    kernel_cmdline: recovery=1
